# Generated by Django 3.2.15 on 2022-10-30 12:33

from django.db import migrations, models
import django.db.models.deletion
import main.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Monograph',
            fields=[
                ('m_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year', models.CharField(choices=[('1399', '1399'), ('1400', '1400'), ('1401', '1401'), ('1402', '1402'), ('1403', '1403'), ('1404', '1404'), ('1405', '1405'), ('1406', '1406'), ('1407', '1407'), ('1408', '1408'), ('1409', '1409'), ('1410', '1410')], max_length=4)),
                ('department', models.CharField(choices=[('SE', 'Software Engineering'), ('IT', 'Information Technology'), ('IS', 'Information System')], max_length=2)),
                ('monograph_title', models.CharField(max_length=255)),
                ('monograph_language', models.CharField(choices=[('EN', 'English'), ('FA', 'Farsi'), ('PA', 'Pashto')], max_length=2)),
                ('monograph_file', models.FileField(upload_to=main.models.file_path_generator_for_monographs, validators=[main.models.validate_monograph_file_extension])),
                ('source_code_files', models.FileField(blank=True, null=True, upload_to=main.models.file_path_generator_for_source_code, validators=[main.models.validate_source_code_file_extension])),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('s_id', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('en_name', models.CharField(max_length=255)),
                ('en_father_name', models.CharField(max_length=255)),
                ('en_last_name', models.CharField(blank=True, max_length=255)),
                ('fa_name', models.CharField(blank=True, max_length=255, null=True)),
                ('fa_father_name', models.CharField(blank=True, max_length=255, null=True)),
                ('fa_last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('monograph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='main.monograph')),
            ],
        ),
    ]
